### ISSUE TITLE
Cannot find the raml annotations?

### ISSUE THREAD

**Issue by ghost** [PaulDevelop/library-raml#1]
PHP v5.6.5
# Symfony 2

Added the library using composer
`"require": {"pauldevelop/library-raml": "dev-master"}`

Tried to use it in sample DefaultController.php
`/**
     * @Route("/raml")
     *
     * @\raml\annotations\Resource(resource="/raml")
     * @\raml\annotations\HttpVerb(verb="GET")
     */
    public function ramlAction(Request $request)
`

When I hit http://<mysite.com>/raml
I get the error.

`[Semantical Error] The annotation "@\raml\annotations\Resource" in method AppBundle\Controller\DefaultController::ramlAction() does not exist, or could not be auto-loaded in /raml-doc/src/AppBundle/Controller/ (which is being imported from "/raml-doc/app/config/routing.yml")
`

**Comment by rscheumann** [comment]
Thank you for getting in touch with me. The annotations don't get mapped to classes; the annotation syntax is used only to enrich the class and methods with meta information that gets parsed by the generator class.

Symfony tries to map the annotations to classes, which causes errors, because those classes simply doesn't exist.

## Solution

According to the symfony website, you can ignore non-symfony annotation like this:

When using another library or program (e.g. Doxygen) that uses annotations, you should place the @IgnoreAnnotation annotation on the class to indicate which annotations Symfony should ignore.
(source: http://symfony.com/doc/current/doctrine.html#add-mapping-information)

HTH

**Comment by ghost** [comment]
Thanks a lot for getting back so fast. I got it working with Symfony with few changes.

Symfony IgnoreAnnotation doesn't like identifiers starting with backslash @\
I had to use something like @raml\annotations.. to get it working
Would it be possible for you to make the namespace configurable in yml or change it to remove the backslash.
`File: Parser.php`
`E.g. $ramlNamespace = 'raml\annotations';`
